config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  resources :dogs
  get '/dashboard', to: 'users#show'

  resources :users, only: [:edit, :update]

  resources :play_dates, except: :destroy

  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'

  resources :locations, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :dog_fact
  add_flash_types :notice, :danger, :success

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def validate_user
    permission_denied unless current_user
  end

  def permission_denied
    redirect_to root_path, alert: 'Please login or sign up.'
  end

  def dog_fact
    DogFactFacade.get_fact
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @page = params[:page]&.to_i || 1
    dogs = DogFacade.dogs(@page)
    @dogs = DogSerializer.new(dogs)

    respond_to do |f|
      f.html
      f.json { render json: { dogs: @dogs } }
    end
  end

  def show
    @dog = DogFacade.find_dog(params[:id])

  end

  def new; end

  def create
    json = DogSerializer.new(dog_params.merge({ user_id: current_user.id })).to_json
    DogFacade.create_dog(json)

    redirect_to dashboard_path, success: 'Dog Created'
  end

  def edit; end

  def update; end

  def delete; end

  private

  def dog_params
    params.permit(:name, :age, :breed, :size, :sex, :vaccinated, :trained, :description)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @page = params[:page]&.to_i || 1
    @locations = LocationFacade.nearby_locations(current_user.location)
    cookies[:invited_dog] = params[:dog_id]
    # @locations = LocationSerializer.new(locations)
    #
    # respond_to do |f|
    #   f.html
    #   f.json { render json: { locations: @locations } }
    # end
  end
end

app/controllers/play_dates_controller.rb
class PlayDatesController < ApplicationController
  before_action :validate_params, only: :create

  def index
    @play_dates = PlayDateFacade.find_for_user(current_user.id)
  end

  def show
    @play_date = PlayDateFacade.all_play_date_info(params[:id])
    @location = LocationFacade.search_by_id(@play_date.location_id)
  end

  def new
    @user_dogs = DogFacade.user_dogs(current_user.id)
    @location = params[:location_id]
  end

  def create
    json = PlayDateSerializer.serialize(playdate_params.merge(playdate_extra_params))
    response = PlayDateFacade.create_play_date(json)

    if !response.empty?
      invalid_redirect('Invalid dog id')
    else
      clear_invited_dog

      redirect_to dashboard_path, success: 'Playdate created, bring your poop bags!'
    end
  end

  def update
    PlayDateFacade.update_play_date(params[:id], params[:status])

    redirect_to dashboard_path
  end

  private

  def playdate_extra_params
    {
      token: current_user.token,
      email: current_user.email,
      invited_dog_id: cookies[:invited_dog]
    }
  end

  def playdate_params
    params.permit(:date, :time, :creator_dog_id, :location_id)
  end

  def clear_invited_dog
    cookies.delete(:invited_dog)
  end

  def valid_date?
    params[:date].present? && Date.today < Date.parse(params[:date])
  end

  def required_params?
    params[:date].present? && params[:time].present? && params[:creator_dog_id].present?
  end

  def validate_params
    invalid_redirect('Invalid params') unless required_params? && valid_date?
  end

  def invalid_redirect(message)
    redirect_to new_play_date_path, alert: message
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_by(email: user_params[:email])
    user.update(user_params)

    session[:user_id] = user.id

    redirect_to dashboard_path
  end

  def destroy
    current_user.update_attribute(:token, nil)

    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def user_params
    {
      google_id: auth_hash['uid'],
      email: auth_hash['info']['email'],
      token: auth_hash['credentials']['token']
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :validate_user

  def edit; end

  def show
    @dogs = DogFacade.user_dogs(current_user.id)
    @pending_invites = PlayDateFacade.find_for_user(current_user.id, 'invited')
  end

  def update
    current_user.update(location: params[:location])
    redirect_to dashboard_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_form.html.erb
<%= form_with url: dogs_path, method: method, local: true do |f| %>
  <div class="form-floating mb-3">
    <%= f.text_field :name, class: 'form-control', id: 'name', placeholder: 'Name' %>
    <%= f.label 'Name', for: 'name' %>
  </div>
  <div class="form-floating mb-3">
    <%= f.number_field :age, class: 'form-control', id: 'age', placeholder: 'Age', min: 1, max: 20 %>
    <%= f.label 'Age', for: 'age' %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :breed, class: 'form-control', id: 'breed', placeholder: 'Breed' %>
    <%= f.label 'Breed', for: 'breed' %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :sex, class: 'form-control', id: 'sex', placeholder: 'Male/Female' %>
    <%= f.label 'Sex', for: 'sex' %>
  </div>
  <div class="form-floating mb-3">
    <%= f.text_field :description, class: 'form-control', id: 'description', placeholder: 'Tell us all about your pooch!' %>
    <%= f.label 'Description', for: 'description' %>
  </div>

    <%= f.label :size, class: 'form-label' %>
    <%= f.select :size, ['small', 'medium', 'large']%>
    <br>
    <%= f.label :vaccinated, class: 'form-label' %>
    <%= f.select :vaccinated, [['no', 'false'], ['yes', 'true']]%>
    <br>
    <%= f.label :trained, class: 'form-label' %>
    <%= f.select :trained, ['no', 'yes']%><br>

  <%= f.submit 'Add Dog', class: 'btn btn-outline-success', id: 'submit-btn' %>
<% end %>

app/views/dogs/index.html.erb
<h1>Dogs!</h1>


<%= react_component('DogList', { dogs: @dogs, page: @page }) %>

app/views/dogs/new.html.erb
<h1>Add Your Dog!</h1>

<%= render partial: 'form', locals: { method: :post } %>

app/views/dogs/show.html.erb
<p><%= @dog.name %>
Breed: <%= @dog.breed %><br>
Age: <%= @dog.age %><br>
Sex: <%= @dog.sex %><br>
Size: <%= @dog.size %><br>
Trained? <%= @dog.trained %><br>
Vaccinated? <%= @dog.vaccinated %><br>
Playdates accepted: <% @dog.accepted_play_dates.each do |pd| %>
Date: <%= pd.date %>
<% end %><br>
Pending playdates: <% @dog.pending_play_dates.each do |pd| %>
Date: <%= pd.date %>
<% end %><br></p>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Bones!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Locations</h1>

<% @locations.each do |l| %>
  <p>Name: <%= l.name %></p>
  <p>Address: <%= l.address %></p>
  <p>Phone: <%= l.phone %></p>
  <p>Rating: <%= l.rating %></p>
  <%= button_to "Select #{l.name} for your playdate!", new_play_date_path, params: { location_id: l.id },  method: :get %>
<% end %>

app/views/play_dates/index.html.erb
<h1>My Playdates!</h1>
<p><% @play_dates.each do |pd| %>
  <%= pd.date %><br>
   <%= link_to "Playdate with #{pd.id}", play_date_path(pd.id) %><br>
<% end %><br></p>

app/views/play_dates/new.html.erb
<h1>New Playdate!</h1>

<%= form_with url: play_dates_path, local: true do |f| %>
  <%= f.hidden_field :location_id, value: @location %>

  <%= f.label :date, "Date of Playdate", class: 'form-label' %>
  <%= f.date_field :date %><br>

  <%= f.label :time, "Time of Playdate", class: 'form-label' %>
  <%= f.time_field :time %><br>

  <%= f.label 'Who is the playdate for?', class: 'form-label' %>
  <%= f.collection_select :creator_dog_id, @user_dogs, :id, :name %>
  <br>
  <%= f.submit "Create Playdate", id: 'submit-btn' %><br>
<% end %>

app/views/play_dates/show.html.erb
<h1>Playdate with <%= @play_date.invited_dog.name %></h1>
<p><%= image_tag @location.image %><br>
<%= @location.name %><br>
<%= @location.address %><br>
<%= @play_date.date %><br>
<%= @play_date.time %><br>
Invited Dog: <%= @play_date.invited_dog.name %><br>
Your Dog: <%= @play_date.creator_dog.name %><br></p>

app/views/shared/_dogfact.html.erb
<!-- <p>Random Dog Fact of the Day!</p>
<# cache 'dog-fact', expires: 1.day do %>
  <p><%# dog_fact %></p><br>
<# end %>
 -->

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:success] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:danger] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <!-- <img src="https://user-images.githubusercontent.com/81711519/140663382-65955342-af6a-4613-9f7c-653cad31c52b.png" alt="Bones Logo" style="width:150px;" class="squared-pill"> -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <div class='navbar-nav'>
      <% if !current_user %>
        <%= link_to 'Sign In with Google',  '/auth/google_oauth2', class: 'nav-link' %>
      <% else %>
        <%= link_to 'Find a Playdate', dogs_path, class: 'nav-link' %>
        <%= link_to 'My Playdates', play_dates_path, class: 'nav-link' %>
      </div>
      <div class='navbar-nav ms-auto'>
        <%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %>
        <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'nav-link' %>
        <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
      </div>
    <% end %>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<h1>Pit Happens!</h1>

<h3>Please update your profile!</h3>

<%= form_with url: user_path(current_user), method: :patch, local: true do |f| %>
  <%= f.hidden_field :location_id, value: @location %>

  <%= f.label :location, "Enter City and State (ex: Denver, CO)", class: 'form-label' %>
  <%= f.text_field :location %><br>

  <%= f.submit "Update Profile", id: 'submit-btn' %><br>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.email %>!</h1>

<div id="location">
  <% if current_user.location.nil? %>
    <%= link_to 'Pawleese add your location!', edit_user_path(current_user) %>
  <% else %>
    <%= link_to 'Find a Playdate for Your Pupper!', dogs_path, class: 'link-dark' %>
  <% end %>
</div>

<br/>
<%= render 'shared/dogfact', cached: true %>
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="container pt-5">
        <% @dogs&.each_slice(2) do |group| %>
        <div class="row">
          <% group.each do |dog| %>
          <div class="col-lg-4">
            <div class="card">
              <div class="card-body">
               <h5 class="card-title"><%= link_to "#{dog.name}", dog_path(dog.id), id: 'card-link' %></h5>
                <p class="card-text"><%= dog&.description %></p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
        <div class="row">
          <%= link_to 'Add new dog', new_dog_path, class: 'nav-link' %>
        </div>
      </div>
    </div>
    <div class="col" id="pending-invites">
      <h3>Pending Invites</h3>
      <% @pending_invites&.each do |invite| %>
        <div class="invite">
          <p class='invite-date'>Date: <%= invite.date %><br><p/>
          <p class='invite-date'>Time: <%= invite.time %><br><p/>
          <%= button_to 'Accept', play_date_path(invite.id), params: { status: 1 }, method: :patch %>
          <%= button_to 'Reject', play_date_path(invite.id), params: { status: 2 }, method: :patch %>
        </div>
        <br>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome <%= current_user&.email %></h1>
<%= render 'shared/dogfact', cached: true %>

<%= button_to 'Sign In with Google',  '/auth/google_oauth2', method: :get, class: 'btn btn-outline-primary' unless current_user %>
<%= button_to 'Sign Out with Google', logout_path, method: :delete, class: 'btn btn-outline-danger' if current_user %>